### PR TITLE
Publish Package Viewer as a package for Delphinus package manager

### PR DESCRIPTION
**Pull request by Pawe1**
Maybe the whole Delphinus project (https://github.com/Memnarch/Delphinus) is not so mature but I think it's just nice idea because it can work directly with GitHub (in opposite to GetIt).

Why?
 - to spread a word about Package Viewer because it's nice tool
 - to make updates quick & easy

The line with keyword "Delphinus-Support" in readme is needed to find Package Viewer repository via GitHub API.

I have called license as "[custom]" - feel free to rename this.

[tested with Delphi 10.2]

Regards
P.

### CODE REVIEW

**Review by DGH2112 — APPROVED** [review]
Your changes are okay, so I'll Approve.

**Comment by DGH2112** [comment]
Let me know if this approval has worked. I do not see any changes on my side (first time I've ever had a pull request from an external source).
regards
Dave.

**Comment by DGH2112** [comment]
Approved but didn't commit a merge. Lets see if that worked.

**Comment by Pawe1** [comment]
Seems to "work on my machine" :wink: 

untitled

Oh... We have to fix long titles a bit :grin:

**Comment by Pawe1** [comment]
In case of any questions ask @Memnarch who is creator of this tool :smile:

**Comment by DGH2112** [comment]
Pawel,
Could you label the package author as David Hoyle, rather than DGH2112?
regards
Dave.

**Comment by Pawe1** [comment]
Huh... It's a good question to @Memnarch

Currently there is no separate field in metadata but maybe it's worth to open new issue?

I have no idea if this is even possible for Bitbucket (Delphinus also have non-direct supports fot it)

**Comment by Pawe1** [comment]
Here is the unit which is responsible for retrieving data from GitHub:
https://github.com/Memnarch/Delphinus/blob/master/DN.PackageProvider.GitHub.pas

Example search results via GitHub API:
https://api.github.com/search/repositories?q="Delphinus-Support"+in:readme&per_page=100

It will probably require extra API calls or extra metadata or something...
From architectural point of view I think that author will have better overview than me.

**Comment by Pawe1** [comment]
There is also problem of GitHub call quota
https://developer.github.com/v3/#rate-limiting

**Comment by Memnarch** [comment]
Hi,
Currently i show the Authoring UserName(The info is pulled from the basic RepoInformation the GithubApi gives). Resolving to the FullName is quite costly atm(means it requires an additional call). Maybe i'll add an extra field to specify such values in the json. For now this is not possible. I am sorry.

**Pull request merged**
